### ISSUE TITLE
Missing wberichte/w47_SwitchTaganduntag.md?

### ISSUE THREAD

**Issue by mrolli** [rosariolm/myjournal#27]
Als Konsument deines Journals wollte ich mir mal wieder deine Wochenberichte anschauen. Derzeit ist aber der Klick auf "Wochenberichte" kaputt, da du im mkdocs.yaml die Datei `w47_SwitchTaganduntag.md` also erste Unterseite verlinkt hast (Navigationstitle ist nur "titel"), die Datei `wberichte/w47_SwitchTaganduntag.md` aber nicht im Repo ist. Kann es sein, dass du das entsprechende `git add` vergessen hast und der Wochenbericht jetzt nur bei dir lokal ist?

**Comment by rosariolm** [comment]
Danke für den Hinweis. Ich habe danach die fehlende Datei noch ge pushed. Habe aber vergessen, dieses Ticket zu schliessen. Ich habe momentan noch Errors, die auftauchen uns sehe nicht, wo der Fehler liegt. Würdest du dir bitte kurz Zeit nehmen und dir das anschauen und mir eine Rückmeldung geben?
