### ISSUE TITLE
Wochenbericht W33 überarbeiten

### ISSUE THREAD

**Issue by mrolli** [rosariolm/myjournal#5]
Die aktuelle Version des Wochenbericht W33 ist ungenügend. Bitte entsprechend der folgenden Punkte verbessern:

* die Kurzanleitung sollte alle Schritte beinhalten von einem frisch installierten macOS bis zum Moment wo die dokumentieren kannst, d.h. es werden folgende Schritte benötigt:
  * Homebrew
  * conda (miniconda)
  * python env erstellen
  * mkdocs und mkdocs-material installieren
  * abschliessen mit kommando, womit man ein Projekt initiiert
* optisch ansprechend gestalten
  * Code in sollte als solcher erkennbar sein, also eingerückt oder von backticks eingeschlossen
  * Böxchen "admonition" eignen sich auch gut zum strukturieren.

**Comment by rosariolm** [comment]
Wurde erledigt. Admonition werden noch hinzugefügt.
