### ISSUE TITLE
mkdocs serve

### ISSUE THREAD

**Issue by rosariolm** [rosariolm/myjournal#51]
:
alternate_style: true

**Comment by mrolli** [comment]
Hoi Laura

Bi mir het das klappet, siehe https://github.com/mrolli/myitjournal/blob/33e9ba6efa4b369b627d4cfd2755dfd20eb511e1/mkdocs.yml#L76

Ds Doppupunkt am ändi vor Zile 76 isch wichtig, sowie natürlech Inhalt und Irückig vor Zile 77.

Gruess, Michael

**Comment by mrolli** [comment]
Ich sehe gerade, dass du gar kein `environment.yml` in deinem Projekt hast, so dass du ganz schnell das Environment löschen und neu erstellen kannst. Erstelle einfach im toplevel Ordner ein File mit folgendem Inhalt

```
name: myjournal
dependencies:
  - python=3
  - pip
  - pip:
      - mkdocs-material
      - mkdocs-git-revision-date-plugin
```

Das Attribut name im File kannst natürlich an deinen Geschmack anpassen. So wird `conda` mit dieser Datei die neuste Version Python3, pip sowie mit dem tool `pip` die Pakedte `mkdocs-material` und `mkdocs-git-revision-date-plugin` und alle deren Abhängigkeiten installieren, also genauj das, was du willst. 

Ab dann kannst du so das ganze Environemnt immer wieder bequem löschen und neu bauen:

```
cd path/to/your/myjournmal
conda env remove --name myjournal
conda env create
```

Ach, und das `environment.yml` natürlich ins git repo aufnehmen und versionieren. ;-)
