### ISSUE TITLE
Error bei Pushen

### ISSUE THREAD

**Issue by rosariolm** [rosariolm/myjournal#53]
Error Anschauen weshalb ich den deploy forcen muss

**Comment by mrolli** [comment]
Ich weiss zwar nicht genau, was du mit "deploy forcen muss" meinst, aber ich kann dir sagen, warum die Action die Seiten nicht mehr bauen kann und die GitHub Action mit einem Fehler beendet. Die letzte Zeile des Tracebacks zeigt es dir.

Falls du versuche möchtest, den Fehler selber zu flicken, dann ignoriere meinen PR, ansonsten sollte der Fehler verschwinden, wenn du meinen PR in deinen main branch übernimmst.
